// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNpcap():Promise<string>;

export function CheckUpdate():Promise<string>;

export function CreateDb(arg1:string):Promise<string>;

export function CreateTask(arg1:string,arg2:number,arg3:Array<string>,arg4:Array<string>):Promise<string>;

export function DeleteTask(arg1:number):Promise<string>;

export function DeleteTaskReport(arg1:number):Promise<string>;

export function DisableBookData():Promise<string>;

export function DisableGetBattleReport():Promise<string>;

export function DisableGetReport():Promise<string>;

export function EnableBookData():Promise<string>;

export function EnableGetBattleReport():Promise<string>;

export function EnableGetReport(arg1:number):Promise<string>;

export function GetDbList():Promise<string>;

export function GetGroupWu():Promise<string>;

export function GetLogs():Promise<string>;

export function GetPlayerTeam(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function GetReportNumByTaskId(arg1:number):Promise<string>;

export function GetTask(arg1:number):Promise<string>;

export function GetTaskList():Promise<string>;

export function GetTeamGroup():Promise<string>;

export function GetTeamUser(arg1:string):Promise<string>;

export function GetTeamWinRate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:number):Promise<string>;

export function GetTeamWinRateByTeam(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:number):Promise<string>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SelectDb(arg1:string):Promise<string>;

export function StatisticsReport(arg1:number):Promise<string>;
